local wk = require("which-key")
wk.add({
{ "<leader>d", desc = "duplicate file" },
{ "<leader>u", desc = "open url" },
{ "<leader>z", desc = "floating terminal" },
{ "<leader>f", desc = "fzf options" },
{ "<leader>g", desc = "grep" },
{ "<leader>G", desc = "grep under cursor" },
{ "<leader>x", desc = "chmod +x" },
{ "<leader>e", desc = "view files" },
{ "<leader>R", desc = "reload config" },
{ "<leader>vs", desc = "vsplit next buf" },
{ "<leader>w", desc = "write" },
{ "<leader>W", desc = "toggle wrap" },
{ "<leader>q", desc = "close buf" },
{ "<leader>Q", desc = "close buf!" },
{ "<leader>U", desc = "close ALL buf" },
{ "<leader>nn", desc = "toggle relative nums" },
{ "<leader>T", desc = "git status" },
{ "<leader>o", desc = "Open current file in default program" },
{ "<leader>cd", desc = "Change the current working directory" },
})
